-- 코드를 입력하세요
SELECT A.FLAVOR
FROM JULY A left JOIN FIRST_HALF B ON A.SHIPMENT_ID = B.SHIPMENT_ID
GROUP BY A.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) DESC LIMIT 3

/*
SELECT JU.FLAVOR
  FROM JULY JU, FIRST_HALF FI
  WHERE JU.FLAVOR = FI.FLAVOR
  GROUP BY JU.FLAVOR
  ORDER BY SUM(JU.TOTAL_ORDER) + SUM(FI.TOTAL_ORDER) DESC
  LIMIT 3
  */